### ISSUE TITLE
A10/A13/A20 - Missing SRAM_BIST_ registers from SRAM Controller

### ISSUE THREAD

**Issue by wingrime** [allwinner-zh/documents#7]
SRAM Controller have BIST unit, definitely present in A10/A13/A20 and seems in others, but nothing in official  docs to be present, please, leave some description about bit fields.

http://linux-sunxi.org/SRAM_Controller_Register_Guide

**Comment by allwinner-zh** [comment]
please take reference of the chapter 1.7.3 in the A20 user manual.
